/* GENERATED by scripts/native_d3d_glue.py -- do not edit. */
#include "nd3d.h"
#define GLUE(VA) void orig_sub_##VA(void); void n_##VA(void); \
    void sub_##VA(void) { if (nd3d_active()) { n_##VA(); return; } orig_sub_##VA(); }
#define GLUE_ORIG(VA) void orig_sub_##VA(void); \
    void sub_##VA(void) { if (nd3d_active()) nd3d_unported(0x##VA##u); orig_sub_##VA(); }

GLUE(00166330)        /*  */
GLUE(001663E0)        /* D3DDevice_CopyRects */
GLUE(001666D0)        /* D3DDevice_SetViewport */
GLUE(00166830)        /* D3DDevice_SetTexture */
GLUE(001669E0)        /* D3DDevice_SetPalette */
GLUE(00166B00)        /* D3DDevice_IsBusy */
GLUE(00166B40)        /* D3DDevice_BeginVisibilityTest */
GLUE(00166BE0)        /* D3DDevice_EndVisibilityTest */
GLUE(00166D10)        /* D3DDevice_SetScissors */
GLUE(00167030)        /* D3DDevice_SetScreenSpaceOffset */
GLUE(001673E0)        /* D3DDevice_SetRenderState_Simple */
GLUE(001676E0)        /* D3DDevice_SetRenderState_EdgeAntiAlias */
GLUE(00167720)        /* D3DDevice_SetRenderState_ShadowFunc */
GLUE(00167760)        /* D3DDevice_SetRenderState_FogColor */
GLUE(001677B0)        /* D3DDevice_SetRenderState_CullMode */
GLUE(00167820)        /* D3DDevice_SetRenderState_FrontFace */
GLUE(00167860)        /* D3DDevice_SetRenderState_NormalizeNormals */
GLUE(001678A0)        /* D3DDevice_SetRenderState_TextureFactor */
GLUE(00167900)        /* D3DDevice_SetRenderState_LineWidth */
GLUE(00167970)        /* D3DDevice_SetRenderState_Dxt1NoiseEnable */
GLUE(00167A70)        /* D3DDevice_SetRenderState_LogicOp */
GLUE(00167AD0)        /* D3DDevice_SetRenderState_FillMode */
GLUE(00167B20)        /* D3DDevice_SetRenderState_BackFillMode */
GLUE(00167B80)        /* D3DDevice_SetRenderState_TwoSidedLighting */
GLUE(00167BF0)        /* D3DDevice_SetRenderState_VertexBlend */
GLUE(00167C40)        /* D3DDevice_SetTextureState_TexCoordIndex */
GLUE(00167D50)        /* D3DDevice_SetTextureState_BumpEnv */
GLUE(00167DC0)        /* D3DDevice_SetTextureState_BorderColor */
GLUE(00167E00)        /* D3DDevice_SetTextureState_ColorKeyColor */
GLUE(001681D0)        /* D3D_CommonSetDebugRegisters */
GLUE(001682A0)        /* D3D_CommonSetRenderTarget */
GLUE(001687F0)        /* D3DDevice_SetRenderState_ZEnable */
GLUE(00168880)        /* D3DDevice_SetRenderState_StencilEnable */
GLUE(00168910)        /* D3DDevice_SetRenderState_StencilFail */
GLUE(00168980)        /* D3DDevice_SetRenderState_YuvEnable */
GLUE(001689B0)        /* D3DDevice_SetRenderState_OcclusionCullEnable */
GLUE(00168A20)        /* D3DDevice_SetRenderState_StencilCullEnable */
GLUE(00168B70)        /* D3DDevice_SetRenderState_MultiSampleAntiAlias */
GLUE(00168BF0)        /* D3DDevice_SetRenderState_MultiSampleMask */
GLUE(00168C40)        /* D3DDevice_SetRenderState_SampleAlpha */
GLUE(00168C90)        /* D3DDevice_Clear */
GLUE(00169790)        /*  */
GLUE(001698B0)        /*  */
GLUE(00169C80)        /*  */
GLUE(00169E60)        /*  */
GLUE(0016A790)        /* D3DDevice_SetVertexShaderConstant1 */
GLUE(0016A7F0)        /* D3DDevice_SetVertexShaderConstant4 */
GLUE(0016A8A0)        /* D3DDevice_SetVertexShaderConstantNotInlineFast */
GLUE(0016AA50)        /* D3DDevice_LoadVertexShader */
GLUE(0016AAB0)        /* D3DDevice_SelectVertexShader */
GLUE(0016AB30)        /* D3DDevice_SetShaderConstantMode */
GLUE(0016AC30)        /*  */
GLUE(0016AD90)        /* D3DDevice_SetVertexShader */
GLUE(0016AF60)        /* D3DDevice_SetPixelShader */
GLUE(0016B160)        /* D3DDevice_SetPixelShaderConstant */
GLUE(0016B4C0)        /* D3DVertexBuffer_Lock2 */
GLUE(0016B620)        /* D3DDevice_DrawVertices */
GLUE(0016B6C0)        /* D3DDevice_DrawIndexedVertices */
GLUE(0016B930)        /* D3DDevice_SetVertexData2f */
GLUE(0016B970)        /* D3DDevice_SetVertexData4f */
GLUE(0016B9D0)        /* D3DDevice_SetVertexDataColor */
GLUE(0016BA20)        /* D3DDevice_Begin */
GLUE(0016BA60)        /* D3DDevice_End */
GLUE(0016BAA0)        /* D3DDevice_RunPushBuffer */
GLUE(0016C940)        /* CDevice_KickOff */
GLUE(0016CA30)        /* D3D_SetFence */
GLUE(0016CAE0)        /* D3D_BlockOnTime */
GLUE(0016CC20)        /* D3D_MakeRequestedSpace_8 */
GLUE(0016CDA0)        /* D3DDevice_MakeSpace */
GLUE(0016CDB0)        /*  */
GLUE(0016CDF0)        /* D3D_KickOffAndWaitForIdle */
GLUE(0016CE10)        /* D3D_BlockOnResource */
GLUE(0016CE90)        /*  */
GLUE(0016CED0)        /*  */
GLUE(0016CFC0)        /*  */
GLUE(0016D2A0)        /* CDevice_InitializeFrameBuffers */
GLUE(0016EC10)        /* CMiniport_IsFlipPending */
GLUE(00170320)        /* D3D_LazySetPointParams */
GLUE(00170490)        /*  */
GLUE(001705F0)        /*  */
GLUE(001707E0)        /*  */
GLUE(001709C0)        /*  */
GLUE(00170E80)        /*  */
GLUE(00171160)        /*  */
GLUE(001714A0)        /*  */
GLUE(00171720)        /* CDevice_SetStateVB */
GLUE(00173A00)        /*  */
GLUE(00165FD0)        /* D3DDevice_GetVisibilityTestResult */
GLUE(0016D800)        /* CDevice_Init (verify) */
GLUE(00166030)        /* D3DDevice_BlockUntilVerticalBlank */
GLUE(00166C40)        /* D3D_SetTileNoWait */

const unsigned nd3d_native_count = 91, nd3d_routine_count = 91;
