/* GENERATED by scripts/nd3d_action_translate.py from
 * nightfire-driving-native/runtime/native/nd3d_api.h -- edit the Driving source
 * and re-run. Addresses are default.xbe (PAL); see
 * native-driving/action-phase0/action-address-map.json. */
/* Native D3D: the contract between the native library routines (n_XXXXXXXX in
 * nd3d_g*.c) and the native D3D11 renderer (nd3d_render.c / nd3d_draw.c).
 *
 * STATE BLOCK. The Xbox D3D library describes its graphics state as 32-bit
 * words (texture format/offset/filter words, combiner words, blend/depth/
 * stencil words, ...), one per state slot, and the shader translators we
 * already have read exactly those words. The native routines therefore store
 * each state word they compute into nd3d_reg[] at the slot index the library
 * uses for it (the word's "method" offset / 4), and the renderer reads that
 * block when a draw happens. Nothing is queued, encoded or decoded: a routine
 * computes a value and stores it, and draws are recorded straight into D3D11.
 *
 * Rules for porting a library routine (see native-driving/phase2/specs):
 *   1. Keep every CPU-side effect of the original exactly: device fields, the
 *      shadow arrays (g_RenderState, texture-stage state), dirty flags 0x1117CC,
 *      resource refcounts / Lock fields, the slot remap bytes 0x1D5BCC, return
 *      value and stack pops.
 *   2. Where the original wrote state word value V for slot M into the push
 *      buffer, write ND3D_SET(M, V) (or ND3D_SETF for floats, ND3D_SETN for a
 *      run of consecutive words), unless M is in the special list below.
 *   3. Special slots are routed to explicit calls instead:
 *        0x0B00..0x0B7C program words       -> nd3d_vp_program_words()
 *        0x0B80..0x0BFC shader constants    -> nd3d_vp_constants()
 *        0x1E9C program load slot / 0x1EA4 constant load slot: track locally in
 *               the routine and pass the slot to the two calls above
 *        0x1EA0 program start               -> nd3d_vp_start()
 *        0x1E94 execution mode              -> nd3d_vp_mode()
 *        0x0A20 / 0x0AF0 viewport offset/scale (4 floats each)
 *                                          -> nd3d_vp_constants(59 / 58, ...)
 *        0x17FC begin/end, 0x1800/0x1808 indices, 0x1810 vertex runs,
 *        0x1818 inline vertices             -> nd3d_draw_* calls
 *        0x1500..0x15FF, 0x1880..0x1AFF immediate vertex attributes
 *                                          -> nd3d_attr()
 *        0x1D94 clear                       -> nd3d_clear() (reads 0x1D8C/0x1D90/
 *               0x1D98/0x1D9C and the surface words, which are ND3D_SET first)
 *        0x0100 / 0x0130 software methods (flip, flip stall) -> nothing; the
 *               native Swap presents directly with nd3d_present()
 *        0x1D6C/0x1D70 / 0x01A4 fence semaphore -> nothing; fences complete at
 *               once (nd3d_core.c)
 *        0x17C8/0x17CC/0x17D0 visibility test -> nd3d_visibility_*()
 *        blit objects (CopyRects)           -> nd3d_copy_rect()
 *        0x0000 object binding, DMA object handles 0x180..0x1A0 -> nothing
 *   4. Addresses in state words are physical, as the library wrote them:
 *      surfaces 0x210/0x214, texture offsets 0x1B00+0x40*s, palettes 0x1B20,
 *      vertex arrays 0x1720+4*s. The renderer turns them into guest addresses.
 *   5. Calling another library routine: a native routine may call another
 *      native routine directly only through the guest ABI helpers below
 *      (nd3d_call*), so stack effects stay exact. Never call orig_sub_X.
 *   6. Never write the push buffer, never touch GPU registers (0xFD......),
 *      never wait. */
#ifndef ND3D_API_H
#define ND3D_API_H
#include "nd3d.h"

/* ---------------------------------------------------------------- state */
#define ND3D_REGS 0x800u                       /* slots 0x0000..0x1FFC */
extern uint32_t nd3d_reg[ND3D_REGS];
#define ND3D_SET(m, v)   (nd3d_reg[((uint32_t)(m) >> 2) & (ND3D_REGS - 1)] = (uint32_t)(v))
static inline void ND3D_SETF(uint32_t m, float f) { uint32_t v; memcpy(&v, &f, 4); ND3D_SET(m, v); }
static inline void ND3D_SETN(uint32_t m, const uint32_t *v, unsigned n) { for (unsigned i = 0; i < n; i++) ND3D_SET(m + 4u * i, v[i]); }
#define ND3D_GET(m)      (nd3d_reg[((uint32_t)(m) >> 2) & (ND3D_REGS - 1)])

/* The static device object (D3D__pDevice always holds this). */
#define ND3D_DEV 0x0010EB80u

/* ------------------------------------------------------- vertex program */
/* Store `ninstr` program instructions (4 words each) starting at program slot `slot`. */
void nd3d_vp_program_words(unsigned slot, const uint32_t *words, unsigned ninstr);
/* Store `count` constants (4 raw float words each) starting at constant slot `slot` (0..191). */
void nd3d_vp_constants(unsigned slot, const uint32_t *words, unsigned count);
void nd3d_vp_start(unsigned slot);
void nd3d_vp_mode(uint32_t mode);

/* --------------------------------------------------------------- draws */
/* Xbox D3DPRIMITIVETYPE values 1..10 (they equal the hardware values). */
void nd3d_draw_arrays(unsigned prim, unsigned start, unsigned count);
/* `indices` is a guest virtual address of `count` 16-bit indices. */
void nd3d_draw_indexed16(unsigned prim, uint32_t indices, unsigned count);
/* Inline (user-pointer) vertices, packed in enabled-attribute order (Action only). */
void nd3d_draw_inline(unsigned prim, const uint32_t *packed, unsigned nv, unsigned dpv);
/* Immediate mode: begin, attribute writes, end. Writing attribute 0 with
 * `emit` != 0 completes one vertex, as the hardware does. */
void nd3d_imm_begin(unsigned prim);
void nd3d_attr(unsigned slot, const float v[4], int emit);
void nd3d_imm_end(void);

/* ------------------------------------------------- clear / copy / present */
/* Clears the current surfaces (state words 0x200..0x214) within x0..x1, y0..y1
 * (inclusive, surface pixels). flags = the library's clear word (0x1D94 value). */
void nd3d_clear(uint32_t flags, unsigned x0, unsigned x1, unsigned y0, unsigned y1,
                uint32_t color, uint32_t zstencil);
/* Rectangle copy between two 32-bit linear surfaces (guest addresses). */
void nd3d_copy_rect(uint32_t src, unsigned spitch, uint32_t dst, unsigned dpitch,
                    unsigned sx, unsigned sy, unsigned dx, unsigned dy, unsigned w, unsigned h);
/* Show the 640x480 surface at guest address `front` on screen. */
void nd3d_present(uint32_t front);

/* ------------------------------------------------- visibility (occlusion) */
void nd3d_visibility_begin(unsigned index);
void nd3d_visibility_end(unsigned index);
/* Returns 1 when the result is ready (always, eventually), with the sample count. */
int  nd3d_visibility_result(unsigned index, uint32_t *count);

/* ------------------------------------------- calling other library routines */
/* Call a routine with the guest stdcall/cdecl ABI: arguments are pushed right to
 * left, then a return address; ecx/edx are set for thiscall/fastcall routines.
 * stdcall routines pop their own arguments; for cdecl use nd3d_call_cdecl. */
uint32_t nd3d_call(void (*fn)(void), uint32_t ecx, uint32_t edx, unsigned nargs, ...);
uint32_t nd3d_call_cdecl(void (*fn)(void), unsigned nargs, ...);
#endif
