/* GENERATED by scripts/nd3d_action_translate.py -- do not edit. */
#include "nd3d.h"
#define GLUE(AVA, DVA) void orig_sub_##AVA(void); void n_##DVA(void); \
    void sub_##AVA(void) { if (nd3d_active()) { n_##DVA(); return; } orig_sub_##AVA(); }

GLUE(00103AA0, 00166030)   /* D3DDevice_BlockUntilVerticalBlank */
GLUE(00103D50, 001666D0)   /* D3DDevice_SetViewport */
GLUE(00103EB0, 00166830)   /* D3DDevice_SetTexture */
GLUE(001040F0, 00166B00)   /* D3DDevice_IsBusy */
GLUE(00104130, 00166C40)   /* D3D_SetTileNoWait */
GLUE(001041F0, 00166D10)   /* D3DDevice_SetScissors */
GLUE(00104390, 00167030)   /* D3DDevice_SetScreenSpaceOffset */
GLUE(00100580, 001673E0)   /* D3DDevice_SetRenderState_Simple */
GLUE(001008E0, 001676E0)   /* D3DDevice_SetRenderState_EdgeAntiAlias */
GLUE(00100920, 00167720)   /* D3DDevice_SetRenderState_ShadowFunc */
GLUE(00100960, 00167760)   /* D3DDevice_SetRenderState_FogColor */
GLUE(001009B0, 001677B0)   /* D3DDevice_SetRenderState_CullMode */
GLUE(00100A20, 00167820)   /* D3DDevice_SetRenderState_FrontFace */
GLUE(00100A60, 00167860)   /* D3DDevice_SetRenderState_NormalizeNormals */
GLUE(00100AA0, 001678A0)   /* D3DDevice_SetRenderState_TextureFactor */
GLUE(00100B00, 00167900)   /* D3DDevice_SetRenderState_LineWidth */
GLUE(00100B70, 00167970)   /* D3DDevice_SetRenderState_Dxt1NoiseEnable */
GLUE(00100C70, 00167A70)   /* D3DDevice_SetRenderState_LogicOp */
GLUE(00100CD0, 00167AD0)   /* D3DDevice_SetRenderState_FillMode */
GLUE(00100D20, 00167B20)   /* D3DDevice_SetRenderState_BackFillMode */
GLUE(00100D80, 00167B80)   /* D3DDevice_SetRenderState_TwoSidedLighting */
GLUE(00100DF0, 00167BF0)   /* D3DDevice_SetRenderState_VertexBlend */
GLUE(00100E40, 00167C40)   /* D3DDevice_SetTextureState_TexCoordIndex */
GLUE(00100F50, 00167D50)   /* D3DDevice_SetTextureState_BumpEnv */
GLUE(00100FC0, 00167DC0)   /* D3DDevice_SetTextureState_BorderColor */
GLUE(00101000, 00167E00)   /* D3DDevice_SetTextureState_ColorKeyColor */
GLUE(001013D0, 001681D0)   /* D3D_CommonSetDebugRegisters */
GLUE(001014A0, 001682A0)   /* D3D_CommonSetRenderTarget */
GLUE(00101A90, 001687F0)   /* D3DDevice_SetRenderState_ZEnable */
GLUE(00101B20, 00168880)   /* D3DDevice_SetRenderState_StencilEnable */
GLUE(00101BB0, 00168910)   /* D3DDevice_SetRenderState_StencilFail */
GLUE(00101C20, 00168980)   /* D3DDevice_SetRenderState_YuvEnable */
GLUE(00101C50, 001689B0)   /* D3DDevice_SetRenderState_OcclusionCullEnable */
GLUE(00101CC0, 00168A20)   /* D3DDevice_SetRenderState_StencilCullEnable */
GLUE(00101E10, 00168B70)   /* D3DDevice_SetRenderState_MultiSampleAntiAlias */
GLUE(00101E90, 00168BF0)   /* D3DDevice_SetRenderState_MultiSampleMask */
GLUE(00101EE0, 00168C40)   /* D3DDevice_SetRenderState_SampleAlpha */
GLUE(001043E0, 00168C90)   /* D3DDevice_Clear */
GLUE(00102F10, 00169790)   /*  */
GLUE(00103030, 001698B0)   /*  */
GLUE(00103400, 00169C80)   /*  */
GLUE(001035E0, 00169E60)   /*  */
GLUE(00102570, 0016A790)   /* D3DDevice_SetVertexShaderConstant1 */
GLUE(001025D0, 0016A7F0)   /* D3DDevice_SetVertexShaderConstant4 */
GLUE(00102680, 0016A8A0)   /* D3DDevice_SetVertexShaderConstantNotInlineFast */
GLUE(00102830, 0016AA50)   /* D3DDevice_LoadVertexShader */
GLUE(00102890, 0016AAB0)   /* D3DDevice_SelectVertexShader */
GLUE(00102910, 0016AB30)   /* D3DDevice_SetShaderConstantMode */
GLUE(00102A10, 0016AC30)   /*  */
GLUE(00102B50, 0016AD90)   /* D3DDevice_SetVertexShader */
GLUE(0010A030, 0016AF60)   /* D3DDevice_SetPixelShader */
GLUE(001049C0, 0016B620)   /* D3DDevice_DrawVertices */
GLUE(00104A60, 0016B6C0)   /* D3DDevice_DrawIndexedVertices */
GLUE(00104CD0, 0016B930)   /* D3DDevice_SetVertexData2f */
GLUE(00104D10, 0016B970)   /* D3DDevice_SetVertexData4f */
GLUE(00104D70, 0016BA20)   /* D3DDevice_Begin */
GLUE(00104DB0, 0016BA60)   /* D3DDevice_End */
GLUE(001064B0, 0016C940)   /* CDevice_KickOff */
GLUE(001065A0, 0016CA30)   /* D3D_SetFence */
GLUE(00106650, 0016CAE0)   /* D3D_BlockOnTime */
GLUE(00106790, 0016CC20)   /* D3D_MakeRequestedSpace_8 */
GLUE(00106910, 0016CDA0)   /* D3DDevice_MakeSpace */
GLUE(00106920, 0016CDB0)   /*  */
GLUE(00106960, 0016CDF0)   /* D3D_KickOffAndWaitForIdle */
GLUE(00106980, 0016CE10)   /* D3D_BlockOnResource */
GLUE(00105190, 0016CED0)   /*  */
GLUE(00105280, 0016CFC0)   /*  */
GLUE(00105560, 0016D2A0)   /* CDevice_InitializeFrameBuffers */
GLUE(00105AC0, 0016D800)   /* CDevice_Init (verify) */
GLUE(0010AFC0, 0016EC10)   /* CMiniport_IsFlipPending */
GLUE(00108950, 00170320)   /* D3D_LazySetPointParams */
GLUE(00108AC0, 00170490)   /*  */
GLUE(00108C20, 001705F0)   /*  */
GLUE(00108E10, 001707E0)   /*  */
GLUE(00108FF0, 001709C0)   /*  */
GLUE(001094B0, 00170E80)   /*  */
GLUE(00109790, 00171160)   /*  */
GLUE(00109AD0, 001714A0)   /*  */
GLUE(00109D50, 00171720)   /* CDevice_SetStateVB */
GLUE(0010D2B0, 00173A00)   /*  */
GLUE(00109EF0, 00109EF0)   /* CDevice_SetStateUP (Action only) */
GLUE(00104860, 00104860)   /* D3DDevice_DrawVerticesUP (Action only) */
GLUE(001019F0, 001019F0)   /* D3DDevice_SetDepthClipPlanes (Action only) */
GLUE(00103CA0, 00103CA0)   /* D3DDevice_GetRasterStatus (Action only) */

const unsigned nd3d_native_count = 84, nd3d_routine_count = 84;
