/* GENERATED by scripts/nd3d_action_translate.py from
 * nightfire-driving-native/runtime/native/nd3d.h -- edit the Driving source
 * and re-run. Addresses are default.xbe (PAL); see
 * native-driving/action-phase0/action-address-map.json. */
/* Native D3D for the Driving engine (phase 2 of native-driving/NATIVE-DRIVING-PLAN.md).
 *
 * The game's statically linked Xbox D3D8 library (XDK 1.0.4831) is replaced
 * routine by routine. Every replaced routine keeps the library's CPU-side
 * bookkeeping (device fields, shadow render/texture state in guest memory) and
 * draws through D3D11 directly instead of writing graphics-chip commands.
 * Nothing here decodes or produces chip command streams.
 *
 * Calling model: a replaced routine is entered exactly like the recompiled one.
 * On entry the guest stack (g_esp) holds the return address, then the stdcall
 * arguments; a few routines take ECX/EDX. The native routine sets g_eax and pops
 * the return address plus its argument bytes, as the original `ret N` does.
 * Callee-saved registers (ebx, esi, edi, ebp) are never touched. */
#ifndef ND3D_H
#define ND3D_H
#include <stdint.h>
#include <stddef.h>
#include <string.h>

#ifdef _MSC_VER
#  define ND3D_TLS __declspec(thread)
#else
#  define ND3D_TLS _Thread_local
#endif
extern ND3D_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern ptrdiff_t g_xbox_mem_offset;

/* Guest memory. */
#define ND3D_GPTR(a)  ((void *)(g_xbox_mem_offset + (uintptr_t)(uint32_t)(a)))
#define G32(a)   (*(volatile uint32_t *)ND3D_GPTR(a))
#define G16(a)   (*(volatile uint16_t *)ND3D_GPTR(a))
#define G8(a)    (*(volatile uint8_t *)ND3D_GPTR(a))
#define GF(a)    (*(volatile float *)ND3D_GPTR(a))

/* Stdcall arguments: ARG(1) is the first argument (ARG(0) is the return address). */
#define ARG(i)   G32(g_esp + 4u * (i))
#define ARGF(i)  GF(g_esp + 4u * (i))
/* Return: set eax and pop the return address plus `argbytes`. */
#define RET(v, argbytes) do { g_eax = (uint32_t)(v); g_esp += 4u + (argbytes); return; } while (0)
#define RETV(argbytes)   do { g_esp += 4u + (argbytes); return; } while (0)

/* Library globals (addresses in Driving.xbe PAL; see native-driving/phase0). */
#define ND3D_PDEVICE        0x001117C0u   /* D3D__pDevice */
#define ND3D_DIRTY          0x001117CCu   /* dirty-flag word, consumed at draw time */
#define ND3D_TEXSTATE       0x001117D0u   /* deferred texture-stage state */
#define ND3D_RENDERSTATE    0x001119D0u   /* g_RenderState[D3DRS index] */
#define ND3D_DEFERRED_RS    0x00111B40u   /* g_DeferredRenderState */
#define ND3D_STREAMS        0x00111C68u   /* g_Stream[] */
static inline uint32_t nd3d_device(void) { return G32(ND3D_PDEVICE); }

/* Device fields (push-buffer bookkeeping that the rest of the library reads). */
#define DEV_PUT        0x00u   /* push-buffer write pointer */
#define DEV_LIMIT      0x04u
#define DEV_FLAGS      0x08u
#define DEV_KICKED     0x2Cu   /* last kicked-off pointer (IsBusy compares it) */
#define DEV_TIME       0x30u   /* fence time counter, +2 per fence */
#define DEV_DONE_PTR   0x34u   /* -> guest dword the GPU writes the completed time to */
#define DEV_PB_START   0x24u
#define DEV_PB_END     0x28u

/* LEAN_NATIVE_D3D=1 selects the native library at start-up; it cannot change later. */
extern int nd3d_on;
void nd3d_init_switch(void);
static inline int nd3d_active(void) { if (nd3d_on < 0) nd3d_init_switch(); return nd3d_on; }

/* A replaced routine that has no native version yet ran in native mode. Logged once
 * per routine; the original then runs (bring-up only: its chip commands are discarded). */
void nd3d_unported(uint32_t va);
void nd3d_log(const char *fmt, ...);
#endif
