/* GENERATED by scripts/nd3d_action_translate.py -- do not edit.
 * Driving routines that default.xbe does not link; referenced only by native
 * helpers of routines Action lacks. Reaching one is a bug: it is logged. */
#include "nd3d.h"
void sub_001661B0(void) { nd3d_log("Driving-only routine sub_001661B0 reached in Action\n"); }
void sub_00166B70(void) { nd3d_log("Driving-only routine sub_00166B70 reached in Action\n"); }
void sub_0016B160(void) { nd3d_log("Driving-only routine sub_0016B160 reached in Action\n"); }
void sub_0016B4C0(void) { nd3d_log("Driving-only routine sub_0016B4C0 reached in Action\n"); }
void sub_0016CE90(void) { nd3d_log("Driving-only routine sub_0016CE90 reached in Action\n"); }
void sub_0016E020(void) { nd3d_log("Driving-only routine sub_0016E020 reached in Action\n"); }
