"""Produce the Action engine's native D3D library from the Driving one.

The native routines are written once, in nightfire-driving-native/runtime/native
(Driving.xbe addresses). Both games link the same XDK 1.0.4831 D3D8 library at
different addresses, so this script writes Action copies with every Driving
address swapped for its default.xbe counterpart, using the address map from the
phase-0 survey (native-driving/action-phase0/action-address-map.json):

  * guest functions  sub_XXXXXXXX / orig_sub_XXXXXXXX -> Action VA
  * data addresses   hex literals listed in the map    -> Action address
  * native routines  n_XXXXXXXX keep their Driving names (the glue maps them)
  * native routines whose Driving routine is not linked into default.xbe are
    dropped (CopyRects, SetPalette, visibility tests, ...)

It also writes runtime/native/nd3d_glue.c (Action sub_ -> Driving-named n_) and
runtime/native/nd3d-action-routines.json (Action VAs to rename in the generated
code). Re-run after any change to the Driving native sources.

Usage: python scripts/nd3d_action_translate.py [--check]
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]                    # nightfire-port-native
PROJ = ROOT.parent
SRC = PROJ / 'nightfire-driving-native/runtime/native'
MAP = PROJ / 'native-driving/action-phase0/action-address-map.json'
OUT = ROOT / 'runtime/native'

amap = json.loads(MAP.read_text())
func = {}
for dva, (ava, how) in amap['all_driving_d3d_function_matches'].items():
    if ava and how.startswith('exact'):
        func[int(dva, 16)] = int(ava, 16)
for dva, v in amap['replace_set'].items():
    if v['action_va']:
        func[int(dva, 16)] = int(v['action_va'], 16)
data = {}
for dva, v in amap['all_native_source_addresses'].items():
    if v['action'] is not None:
        data[int(dva, 16)] = int(v['action'], 16)
replace = {int(k, 16): v for k, v in amap['replace_set'].items()}
dropped = {va for va, v in replace.items() if not v['action_va']}

unresolved = set()

def sub_name(m):
    prefix, hexva = m.group(1), m.group(2)
    va = int(hexva, 16)
    if va in func:
        return f'{prefix}{func[va]:08X}'
    unresolved.add(f'{prefix}{hexva}')
    return m.group(0)

def literal(m):
    text, digits, suffix = m.group(0), m.group(1), m.group(2)
    va = int(digits, 16)
    if va < 0x18000 or va not in data:
        return text
    return f'0x{data[va]:0{len(digits)}X}{suffix}'

def drop_functions(src):
    """Remove top-level `void n_X(void)` definitions of routines Action lacks."""
    lines = src.split('\n')
    out, i, removed = [], 0, []
    while i < len(lines):
        m = re.match(r'^void n_([0-9A-F]{8})\(void\)\s*$', lines[i])
        if m and int(m.group(1), 16) in dropped and i + 1 < len(lines) and lines[i + 1].startswith('{'):
            j = i + 1
            while j < len(lines) and not lines[j].startswith('}'):
                j += 1
            # also drop the comment block directly above
            while out and (out[-1].startswith((' *', '/*')) or out[-1].strip() == '*/'):
                out.pop()
            removed.append(m.group(1))
            i = j + 1
            continue
        out.append(lines[i])
        i += 1
    return '\n'.join(out), removed

def translate(text):
    text = re.sub(r'\b((?:orig_)?sub_)([0-9A-F]{8})\b', sub_name, text)
    text = re.sub(r'\b0x([0-9A-Fa-f]{5,8})([uU]?)\b', literal, text)
    return text

def main():
    check = '--check' in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    header = ('/* GENERATED by scripts/nd3d_action_translate.py from\n'
              ' * nightfire-driving-native/runtime/native/{name} -- edit the Driving source\n'
              ' * and re-run. Addresses are default.xbe (PAL); see\n'
              ' * native-driving/action-phase0/action-address-map.json. */\n')
    removed_all, natives = [], set()
    for f in sorted(SRC.iterdir()):
        if f.suffix not in ('.c', '.h') or f.name == 'nd3d_glue.c':
            continue
        text = f.read_text()
        text, removed = drop_functions(text)
        removed_all += removed
        natives |= {int(x, 16) for x in re.findall(r'^void n_([0-9A-F]{8})\(void\)', text, re.M)}
        text = translate(text)
        if not check:
            (OUT / f.name).write_text(header.format(name=f.name) + text)
    rows = []
    glue = ['/* GENERATED by scripts/nd3d_action_translate.py -- do not edit. */',
            '#include "nd3d.h"',
            '#define GLUE(AVA, DVA) void orig_sub_##AVA(void); void n_##DVA(void); \\',
            '    void sub_##AVA(void) { if (nd3d_active()) { n_##DVA(); return; } orig_sub_##AVA(); }',
            '']
    for dva in sorted(replace):
        v = replace[dva]
        if not v['action_va'] or dva not in natives:
            continue
        ava = int(v['action_va'], 16)
        glue.append(f'GLUE({ava:08X}, {dva:08X})   /* {v["name"]} */')
        rows.append({'va': f'0x{ava:X}', 'driving_va': f'0x{dva:X}', 'name': v['name']})
    # Action-only routines (runtime/native_action/*.c, written with default.xbe addresses).
    for r in json.loads((ROOT / 'runtime/native_action/nd3d-action-only.json').read_text()):
        ava = int(r['va'], 16)
        glue.append(f'GLUE({ava:08X}, {ava:08X})   /* {r["name"]} (Action only) */')
        rows.append({'va': f'0x{ava:X}', 'driving_va': None, 'name': r['name']})
    glue.append('')
    glue.append(f'const unsigned nd3d_native_count = {len(rows)}, nd3d_routine_count = {len(rows)};')
    if not check:
        (OUT / 'nd3d_glue.c').write_text('\n'.join(glue) + '\n')
        (OUT / 'nd3d-action-routines.json').write_text(json.dumps(rows, indent=1))
    # Driving-only guest functions still named by helpers that only the dropped
    # routines use: defined here so the Action build links (they log if ever run).
    stubs = ['/* GENERATED by scripts/nd3d_action_translate.py -- do not edit.',
             ' * Driving routines that default.xbe does not link; referenced only by native',
             ' * helpers of routines Action lacks. Reaching one is a bug: it is logged. */',
             '#include "nd3d.h"']
    for name in sorted(n for n in unresolved if n.startswith('sub_')):
        stubs.append(f'void {name}(void) {{ nd3d_log("Driving-only routine {name} reached in Action\\n"); }}')
    if not check:
        (OUT / 'nd3d_action_stubs.c').write_text('\n'.join(stubs) + '\n')
    print(f'{len(rows)} routines glued; dropped natives: {", ".join(sorted(removed_all)) or "none"}')
    if unresolved:
        print('UNRESOLVED guest functions (no default.xbe counterpart):', ' '.join(sorted(unresolved)))
    leftovers = set()
    for f in OUT.glob('*.[ch]'):
        for m in re.finditer(r'\b0x(1[5-9A-D][0-9A-Fa-f]{4})\b', f.read_text()):
            va = int(m.group(1), 16)
            if va not in data.values() and va not in data:
                leftovers.add(m.group(1))
    if leftovers:
        print('Driving-range literals left untranslated (check by hand):', ' '.join(sorted(leftovers)))

main()
