"""Generate runtime/native/nd3d_glue.c: one definition sub_XXXXXXXX per replaced
D3D routine (see scripts/native_d3d_rename.py). A native implementation is a
function `void n_XXXXXXXX(void)` in runtime/native/*.c; routines without one fall
back to orig_sub_XXXXXXXX and are reported once in native mode. Re-run after
adding implementations."""
import json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
NAT = ROOT / 'runtime/native'
BS = chr(92)
rows = json.loads((NAT / 'nd3d-replace-set.json').read_text())
impl = set()
for f in NAT.glob('*.c'):
    if f.name == 'nd3d_glue.c':
        continue
    impl |= {int(m, 16) for m in re.findall(r'^void n_([0-9A-F]{8})\(void\)', f.read_text(), re.M)}
out = ['/* GENERATED by scripts/native_d3d_glue.py -- do not edit. */',
       '#include "nd3d.h"',
       '#define GLUE(VA) void orig_sub_##VA(void); void n_##VA(void); ' + BS,
       '    void sub_##VA(void) { if (nd3d_active()) { n_##VA(); return; } orig_sub_##VA(); }',
       '#define GLUE_ORIG(VA) void orig_sub_##VA(void); ' + BS,
       '    void sub_##VA(void) { if (nd3d_active()) nd3d_unported(0x##VA##u); orig_sub_##VA(); }',
       '']
n = 0
for r in rows:
    va = int(r['va'], 16)
    name = r.get('name') or ''
    if va in impl:
        out.append(f'GLUE({va:08X})        /* {name} */')
        n += 1
    else:
        out.append(f'GLUE_ORIG({va:08X})   /* {name} -- not native yet */')
out.append('')
out.append(f'const unsigned nd3d_native_count = {n}, nd3d_routine_count = {len(rows)};')
(NAT / 'nd3d_glue.c').write_text('\n'.join(out) + '\n')
print(f'{n} of {len(rows)} routines native')
