@echo off
setlocal
cd /d "%~dp0"
call output-paths.cmd
set "NIGHTFIRE_BUILD_CONFIG=RelWithDebInfo"
cmake -S . -B build-windows -DNIGHTFIRE_TEXTURE_REUSE98=OFF -DNIGHTFIRE_GPU_TIMING_DIAGNOSTIC=OFF -DNIGHTFIRE_VERTEX_REUSE105_DIAGNOSTIC=OFF -DNIGHTFIRE_VERTEX_CACHE106=OFF -DNIGHTFIRE_VERTEX_CACHE107=OFF -DNIGHTFIRE_SURFACE_COHERENCE108=ON -DNIGHTFIRE_COLOR_REUPLOAD109_DIAGNOSTIC=OFF -DNIGHTFIRE_COLOR_REUSE110=OFF -DNIGHTFIRE_EARLY_SUBMIT113=ON -DNIGHTFIRE_TEXTURE_EQUAL114=ON -DNIGHTFIRE_OBSERVER_OUTLINE104=ON -DNIGHTFIRE_TEXTURE_DECODE100=ON -DNIGHTFIRE_SHADER_CACHE99=ON -DNIGHTFIRE_GPU_BLEND97=ON -DNIGHTFIRE_GPU_FALLBACK96=ON -DNIGHTFIRE_GAME_PACING93=OFF -DNIGHTFIRE_GAME_RATE94=ON -DNIGHTFIRE_DIRECT_VERTEX88=ON -DNIGHTFIRE_DIRECT_DEFAULT90=ON -DNIGHTFIRE_COMPACT_VERTEX91=ON -DNIGHTFIRE_VERTEX_BATCH92=ON -DNIGHTFIRE_FRAME_PROBE_DIAGNOSTIC=OFF -DNIGHTFIRE_HOST_EXE_NAME=nightfire_diagnostic > logs\build-main-configure.log 2>&1
if errorlevel 1 (
  type logs\build-main-configure.log
  exit /b 1
)
call build-windows.cmd
exit /b %ERRORLEVEL%
